[dnb.social]
[dnb.social.sharebuttons]
icons = true
sharetext = true
networks = [
  "facebook",
  "twitter",
  "tumblr",
  "email",
  "pinterest",
  "linkedin",
  "reddit",
  "xing",
  "whatsapp",
  "hackernews",
  "vkontakte",
  "telegram",
]
